ALTER WAREHOUSE COMPUTE_WH
  SET
    WAREHOUSE_SIZE = 'X-SMALL',
    AUTO_SUSPEND   = 60,
    AUTO_RESUME    = TRUE;

CREATE OR REPLACE WAREHOUSE VW_GENAI
  WITH
    WAREHOUSE_SIZE    = 'X-SMALL',
    WAREHOUSE_TYPE    = 'STANDARD',
    AUTO_SUSPEND      = 30,
    AUTO_RESUME       = TRUE,
    MIN_CLUSTER_COUNT = 1,
    MAX_CLUSTER_COUNT = 3,
    SCALING_POLICY    = 'STANDARD';

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

CREATE OR REPLACE DATABASE BD_EMPRESA;
CREATE SCHEMA BRONZE;
CREATE SCHEMA SILVER;
CREATE SCHEMA GOLD;

USE WAREHOUSE VW_GENAI;
USE DATABASE BD_EMPRESA;
USE SCHEMA GOLD;

create or replace api integration mggsnowflake_git
    api_provider = git_https_api
    api_allowed_prefixes = ('https://github.com/mariogalvis/mggsnowflake')
    enabled = true
    allowed_authentication_secrets = all;

CREATE or replace GIT REPOSITORY mggsnowflake_git 
	ORIGIN = 'https://github.com/mariogalvis/mggsnowflake' 
	API_INTEGRATION = 'MGGSNOWFLAKE_GIT';

CREATE OR REPLACE STAGE mgg_files
  DIRECTORY  = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

COPY FILES INTO @mgg_files
  FROM @mggsnowflake_git/branches/main/files/
  PATTERN = '.*';

ALTER STAGE mgg_files REFRESH;

ALTER WAREHOUSE VW_GENAI SET WAREHOUSE_SIZE = 'X-LARGE' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

EXECUTE IMMEDIATE FROM @BD_EMPRESA.GOLD.MGG_FILES/sql/utilities.sql;

EXECUTE IMMEDIATE FROM @BD_EMPRESA.GOLD.MGG_FILES/sql/cortex_search.sql;

EXECUTE IMMEDIATE FROM @BD_EMPRESA.GOLD.MGG_FILES/sql/cortex_analyst.sql;

EXECUTE IMMEDIATE FROM @BD_EMPRESA.GOLD.MGG_FILES/sql/dynamic_tables.sql;

EXECUTE IMMEDIATE FROM @BD_EMPRESA.GOLD.MGG_FILES/sql/snowflake_intelligence.sql;

ALTER WAREHOUSE VW_GENAI SET WAREHOUSE_SIZE = 'X-SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

ALTER WAREHOUSE VW_ADVANCED_ANALYTICS
  SET
    WAREHOUSE_SIZE = 'X-SMALL',
    AUTO_SUSPEND   = 60,
    AUTO_RESUME    = TRUE;

DECLARE user_name STRING;

BEGIN
  user_name := CURRENT_USER();

  EXECUTE IMMEDIATE
    'ALTER USER "' || user_name || '" 
       SET DEFAULT_WAREHOUSE = ''VW_GENAI'', 
           DEFAULT_ROLE = ''ACCOUNTADMIN''';
END;


